### ISSUE TITLE
'ambiguous argument' error

### ISSUE THREAD

**Issue by alexwhitman** [janinko/ghprb#147]
Using `1.12` with Jenkins `1.532.2` I'm getting the following error when trying to build a pull request:

```
GitHub pull request #4 of commit 74a2717e4ec7dee64daee86e3962a29c8b943012 automatically merged.
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/Jenkins Test Pull Requests/workspace
 > git rev-parse --is-inside-work-tree
Fetching changes from the remote Git repository
 > git config remote.origin.url git@hpst:user/jenkins-test.git
Fetching upstream changes from git@host:user/jenkins-test.git
 > git --version
 > git fetch --tags --progress git@host:user/jenkins-test.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/pr/4/merge^{commit}
FATAL: Command "git rev-parse origin/pr/4/merge^{commit}" returned status code 128:
stdout: origin/pr/4/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/4/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions

hudson.plugins.git.GitException: Command "git rev-parse origin/pr/4/merge^{commit}" returned status code 128:
stdout: origin/pr/4/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/4/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1301)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1277)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1273)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1078)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1088)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:490)
    at hudson.plugins.git.GitAPI.revParse(GitAPI.java:257)
    at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:83)
    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:789)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:881)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1411)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:652)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:561)
    at hudson.model.Run.execute(Run.java:1665)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:246)
```

See also https://issues.jenkins-ci.org/browse/JENKINS-22253

**Comment by GBeauny4D** [comment]
I've the same issue and dunno why it's hapenning : 

git rev-parse origin/refs/tags/v0.0.1^
{commit} # timeout=10
FATAL: Command "git rev-parse origin/refs/tags/v0.0.1^{commit}

" returned status code 128:
stdout: origin/refs/tags/v0.0.1^
{commit}

stderr: fatal: ambiguous argument 'origin/refs/tags/v0.0.1^{commit}

': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions

hudson.plugins.git.GitException: Command "git rev-parse origin/refs/tags/v0.0.1^
{commit}" returned status code 128:
stdout: origin/refs/tags/v0.0.1^{commit}

stderr: fatal: ambiguous argument 'origin/refs/tags/v0.0.1^
{commit}

': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions

Plugin (jenkins-gitlab-merge-request-builder-plugin) version i'm using: 1.2.2
Link : https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin
Jenkins version: 1.610
Git version: 1.7.10.4
Gitlab version: 1.7.9

Looks like my refspec isn't good, i specified into jenkins : +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*. 

I don't understand why my rev-parse is done on : "git rev-parse origin/refs/tags/v0.0.1^{commit}" and not on "git rev-parse refs/tags/v0.0.1^{commit}"

Thanks a lot guys.

**Comment by DavidTanner** [comment]
@GBeauny4D Check out http://stackoverflow.com/a/22747145/455536

**Comment by GBeauny** [comment]
Thanks
