### ISSUE TITLE
Pull request trigger throws NPE ...

### ISSUE THREAD

**Issue by kedarmhaswade** [janinko/ghprb#177]
Environment: 
Jenkins - 1.574
ghprb: 1.13-1

Configured the GH project, as well as the jenkins hook url correctly. Jenkins GitHub Plugin correctly identifies the push notifications. However, when a PR is created, that's not recognized by this plugin. I see the following stack trace:
```
    java.lang.NullPointerException
    at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:132)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
```

**Comment by DavidTanner** [comment]
Json was just added to the webhook logic, and i am going to get it released in the next week.

**Comment by donbecker** [comment]
@DavidTanner was this ever fixed? 

I'm seeing the same behavior, some of my jobs using the GHPRB plugin work with GitHub Webhooks, and some do not. I looked thru the commit history and found no references to fixes for this issue (#177).

Let me know if you need more info from me to help. Thanks!

**Comment by donbecker** [comment]
FYI, I ended up with the "helper is null" exception on jobs that did not have "GitHub project" set.

**Comment by DavidTanner** [comment]
As far as I know, the Github Project has to be set for the plugin to work correctly.

**Comment by donbecker** [comment]
@DavidTanner thanks for the reply, yes it seems to be working now.
