### ISSUE TITLE
Issue with Github Enterprise

### ISSUE THREAD

**Issue by mytrile** [janinko/ghprb#202]
Hey, guys.

I've installed the plugin, but even if I enter the github credentials I still get the error:

```
Setting commit status on GitHub for https://xxxxxxxxxx/username/repo_name/commit/xxxxxxxxxxxxxxxxxxxxxxxxx
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.FileNotFoundException: https://xxxxxxxx/api/v3/repos/username/repo_name/statuses/xxxxxxxxxxxxxxxxxxxxxxxxx
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1434)
  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
  at org.kohsuke.github.Requester.parse(Requester.java:383)
  at org.kohsuke.github.Requester._to(Requester.java:185)
  at org.kohsuke.github.Requester.to(Requester.java:160)
  at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:702)
  at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:714)
  at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:76)
  at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
  at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
  at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:754)
  at hudson.model.Build$BuildExecution.post2(Build.java:183)
  at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:707)
  at hudson.model.Run.execute(Run.java:1690)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
  at hudson.model.ResourceController.execute(ResourceController.java:88)
  at hudson.model.Executor.run(Executor.java:246)
Finished: FAILURE
```

I've intentionally replaced username/repo/sha

**Comment by DavidTanner** [comment]
The file not found exception is caused by either a bad link, or the credentials you are using don't have the right permissions.
