### ISSUE TITLE
build status not updating pull request; log message not very helpful

### ISSUE THREAD

**Issue by ncolton** [janinko/ghprb#203]
When the build runs, I managed to get this information in Jenkins logs:

```
Could not update commit status of the Pull Request on GitHub.
java.io.FileNotFoundException: https://api.github.com/repos/:organization/:repo/statuses/:commit_hash
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1401)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
```

After a great deal of troubleshooting, I eventually found that the reason some repos were getting pull requests updated with status, and others were not, was that the GitHub user used by Jenkins did not have write permissions to the repositories which were not getting status updates.

I suspect it is throwing this error as HTTP status codes 404 and 403 are thrown by the API so as to not reveal information about the repositories, so this results in the 404 being interpreted as FileNotFound. It would be _incredibly_ helpful if, rather than a FileNotFoundException, a message indicating the permissions problem is the cause so that the issue can be remedied by administrative changes with a lot less wasted time.

**Comment by DavidTanner** [comment]
I have added some logging so that the console log of the build will reflect that the error is probably because of bad credentials.
