### ISSUE TITLE
Trigger phrase build not working - Could not retrieve GitHub repository named ...

### ISSUE THREAD

**Issue by mtomas** [janinko/ghprb#246]
Hello

I am trying to trigger build by setting test phrase to PR comment.

In general settings there is Test phrase set to `.*test\W+this\W+please.*`
In job config in advanced section under Build triggers I set Test phrase field to `test this please`

Webhooks after commenting with message that matches this test prhase config is being set and detected in logs
```
Apr 08, 2015 6:47:05 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Got payload event: issue_comment
Apr 08, 2015 6:47:05 PM INFO org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Checking issue comment 'org.kohsuke.github.GHIssueComment@a517e0d' for repo ScalaConsultants/fow-backend
```

however build does not get run and I am getting following in the Jenkins log:

```
Apr 08, 2015 7:09:00 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
Could not retrieve GitHub repository named ScalaConsultants/fow-backend.git (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: https://api.github.com/repos/ScalaConsultants/fow-backend.git
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:383)
	at org.kohsuke.github.Requester._to(Requester.java:185)
	at org.kohsuke.github.Requester.to(Requester.java:160)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:324)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:62)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:72)
	at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:97)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:140)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

GitHub PR plugin triggers build of job nicely when PR is being created or another commit is added to the PR.

Any ideas why it does not work when trying to run it through test phrase ??

Thanks.

**Comment by DavidTanner** [comment]
Check the repo portion, it shouldn't have .git in it.  It should just match what you would put in your browser.

**Comment by rmldsky** [comment]
Experiencing the sam issue. GH projects/jobs on Jenkins are configured correctly and in general work, thou this message appear in logs. What I guess is that ghprb does not authenticate correctly when querying GitHub API, hence cannot get info about private repositories? Still looking into our setup to check if this is something we've messed up with credentials.

**Comment by DavidTanner** [comment]
Please check again with 1.24.8, there are additional checks you can use on the global config page to see if your credentials have access to a particular repo, and see what permissions you have.

**Comment by v1v** [comment]
I've just seen this issue, and I've found when using ".git" the Jenkins instance gets unresponsive since it's trying over and over to find that particular project. I know that's a misconfiguration within the Jenkins job, but i don't think it should hammer the jenkins instance.

```
SEVERE: Could not retrieve GitHub repository named PCT-XYZ/project.git (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.6/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:511)
	at org.kohsuke.github.Requester._to(Requester.java:250)
	at org.kohsuke.github.Requester.to(Requester.java:196)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:335)
```

I'm actually using 	1.29 version

**Comment by ericgoedtel** [comment]
it would be nice if this would tell you *which* job was misconfigured. I have a lot of jobs that reuse the same repository and it is unpleasant to go through them and locate the one that is misconfigured.

**Comment by indrgun** [comment]
I experienced the same issue.  I do not see the error in the Jenkins log with GitHub repo set to public and it works fine with the public one.  In short, this issue happens with private repo.  I changed the test repo from private to public and suddenly the PR started to trigger the build.

The version of Github related plugins I am using are:

GitHub API Plugin
This plugin provides GitHub API for other plugins.
version: 1.72			

	
GitHub plugin
This plugin integrates GitHub to Jenkins.
version: 1.17.1			

	
GitHub Pull Request Builder
This plugin builds pull requests in github and report results.
version: 1.31.2	 

Is this a regression?  The Github project configured in the field does not have ".git" in the end.

Thank you

**Comment by giorgenes** [comment]
+1

**Comment by daniilyar** [comment]
Reproduces for us as well. Upgrading to the last version of Jenkins and ghprb does not help.
