### ISSUE TITLE
Jenkins stopped building on pull requests

### ISSUE THREAD

**Issue by surrehman76** [janinko/ghprb#279]
with Jenkins 1.616 ghprb 1.22.1 (also downgraded to 1.21) it seems all perfectly running Jenkins jobs stopped working. Jenkins logs  show:
ARNING hudson.triggers.Trigger$Cron doRun

Cron thread throw an exception
java.lang.NullPointerException
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:263)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Jun 02, 2015 2:34:00 PM WARNING hudson.triggers.Trigger$Cron doRun

Cron thread throw an exception
java.lang.NullPointerException
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:263)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Not sure this is related. Has someone seen it? Any solutions even downgrade if its soemthing obvious?

**Comment by DavidTanner** [comment]
Found the issue here also.  It has to do with projects where the start() method in the trigger doesn't call its super method.  Fixed in 1.22.2.  It should be up to https://updates.jenkins-ci.org/download/plugins/ghprb/ soon.
