### ISSUE TITLE
Status updated when triggered/started but not when finished

### ISSUE THREAD

**Issue by kentor** [janinko/ghprb#290]
The status of the commit gets updated when the build is trigged and started. I see this in the jenkins logs:

```
GitHub pull request #3492 of commit b56319e17ce84c9cca7f312f18327007be91a410, no merge conflicts.
Setting status of b56319e17ce84c9cca7f312f18327007be91a410 to PENDING with url <snip>: 'Build Started sha1 is merged.'
```

But I can't figure out why the status is not being set when the build finishes. I've enabled the "Set build status on Github commit" post-build action. My other post-build actions work. How do I go about debugging this?

**Comment by longcao** [comment]
FWIW, I'm also seeing this on Jenkins 1.617, ghprb 1.24.1, github-api 1.68, git plugin 2.3.5, credentials 1.22, plain credentials 1.1 (fully updated everything). It updates when triggered and started, but doesn't update after that.

Here's a suspicious looking stack trace from the Jenkins logs that comes right after the job is a 'SUCCESS', I am not sure what it means, though:

```
Jun 22, 2015 11:54:45 AM INFO hudson.model.Run execute
$APP pr #6 main build action completed: SUCCESS
Jun 22, 2015 11:54:46 AM WARNING hudson.model.listeners.RunListener report
RunListener failed
java.lang.NoClassDefFoundError: hudson/tasks/test/TestObject
	at org.jenkinsci.plugins.ghprb.manager.factory.GhprbBuildManagerFactoryUtil.getBuildManager(GhprbBuildManagerFactoryUtil.java:37)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:151)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.test.TestObject
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
```

**Comment by DavidTanner** [comment]
@kentor add a build log to Manage Jenkins -> System Log add a logger for org.jenkinsci.plugins.ghprb

@longcao I am not familiar with the build flow stuff at all, maybe @mdelapenya could shed some light on it?

**Comment by mdelapenya** [comment]
Hi @longcao, are you deploying a custom package of ghprb or just the package from Jenkins repositories?

The NoClassDefFoundError appears when a linkage error is present, so maybe the code was compiled with TestObject in classpath, and fails in runtime because the class is not present.

Reviewing GhprbBuildManagerFactoryUtil's code, it seems not related to tests, so I am afraid I can't add any clarity on it at this moment.

**Comment by longcao** [comment]
@mdelapenya Thanks for the response- I'm using just the vanilla packages installed through Jenkins.

**Comment by kentor** [comment]
Thanks @DavidTanner, I added the logger and I see this:

```
Jun 26, 2015 8:32:56 AM FINE org.jenkinsci.plugins.ghprb.GhprbPullRequest
New commit. Sha: 6f9a498ffc11a48386a5cf5038968991d50c731d => a0ed402759baff8a24d47a4f8cfb6825e0508eb8
Jun 26, 2015 8:32:56 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jun 26, 2015 8:32:56 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Author email was not set, trying to set it to null
Jun 26, 2015 8:32:56 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jun 26, 2015 8:32:56 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
Jun 26, 2015 8:32:56 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbTrigger getRepository
The ghprb trigger for xxxxxx-pr-notifier wasn't properly started - helper is null
Jun 26, 2015 8:32:56 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Jun 26, 2015 8:32:56 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Unable to process web hook for: xxxxxx-pr-notifier
java.lang.NullPointerException
  at org.jenkinsci.plugins.ghprb.GhprbWebHook.matchRepo(GhprbWebHook.java:105)
  at org.jenkinsci.plugins.ghprb.GhprbWebHook.handleWebHook(GhprbWebHook.java:59)
  at org.jenkinsci.plugins.ghprb.GhprbRootAction.doIndex(GhprbRootAction.java:89)
```

so this exception occurs near the beginning of running the build. not really sure what it means or why it's trying to process web hooks. also not sure if it has to do with the post build action failing to trigger

**Comment by mdelapenya** [comment]
Hey @longcao, is the junit-plugin installed on your server?

**Comment by longcao** [comment]
@mdelapenya it isn't, I'll try upgrading to the latest and enabling it to see if it works, will report back later.

**Comment by trlinkin** [comment]
@mdelapenya @longcao I ad the same problem, made sure to have the latest Junit plugin and it's all good now.

**Comment by mdelapenya** [comment]
Good to know!!! Thanks for your feedback! :)

**Comment by longcao** [comment]
@mdelapenya @trlinkin Happy to report that enabling the junit plugin on the latest ghprb version (1.24.5) fixed everything. I suggest adding it to required dependencies!

**Comment by DavidTanner** [comment]
@kentor I think this bug got hijacked, but can you update to the latest and check the logs again?

**Comment by kentor** [comment]
I think this has been fixed for me after updating. Thanks! I guess I'll close this out.

**Comment by DavidTanner** [comment]
Thanks!

**Comment by gbrun** [comment]
Hi, I understand this issue has been closed, but I am going through the exact same problem. 
I have installed version 1.30.4 of the plugin through Jenkins plugin manager, and I do have JUnit plugin installed (v1.10). 

Whenever the build succeeds, I get the following error in our logs:
```
RunListener failed
java.lang.NoClassDefFoundError: hudson/tasks/test/TestObject
	at org.jenkinsci.plugins.ghprb.manager.factory.GhprbBuildManagerFactoryUtil.getBuildManager(GhprbBuildManagerFactoryUtil.java:37)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:177)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:186)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.test.TestObject
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

**Comment by vjames19** [comment]
@gbrun I'm having the same error as you.

```
May 09, 2016 2:59:19 PM WARNING hudson.model.listeners.RunListener report
RunListener failed
java.lang.NoClassDefFoundError: hudson/tasks/test/TestObject
	at org.jenkinsci.plugins.ghprb.manager.factory.GhprbBuildManagerFactoryUtil.getBuildManager(GhprbBuildManagerFactoryUtil.java:37)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:202)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:192)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.test.TestObject
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more```

**Comment by gbrun** [comment]
@vjames19 
I was able to fix this by force enabling the junit plugin. For some reason, it was disabled and greyed out and I had not noticed it. If that is what's happening with you too, remove the plugins/junit.jpi.disabled file and enable in the plugins manager. 
Hope it helps.
