### ISSUE TITLE
NullPointerException in GhprbSimpleStatus.java:134

### ISSUE THREAD

**Issue by alexkli** [janinko/ghprb#295]
Using v1.24, upon build completion it throws the NPE below. Github doesn't get notified, build status there stays on "Build Started" forever.

```
Jun 25, 2015 7:47:06 PM WARNING hudson.model.listeners.RunListener report
RunListener failed
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:134)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	at hudson.model.Run.execute(Run.java:1802)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by DavidTanner** [comment]
Fixed in 1.24.1

**Comment by alexkli** [comment]
I could swear I was looking at the master version of the file :)

**Comment by DavidTanner** [comment]
You were, but I usually do deploys to jenkinsci, then merge them back here to janinko.

**Comment by alexkli** [comment]
Ah, got it. Anyway, thanks for all the work!
