### ISSUE TITLE
Merger - Null pointer if build is triggered when pull request started automatically IsAdmin isOwnCode

### ISSUE THREAD

**Issue by benSlaughter** [janinko/ghprb#298]
When a build is triggered automatically then the merger can fail if is own code or is admin merger options are used.

Setup:
Enabled:
 - Build every pull request automatically without asking (Dangerous!).
 - Only Admin can merge code
 - Disallow merging own code?

Stack:
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbPullRequestMerge.isOwnCode(GhprbPullRequestMerge.java:191)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequestMerge.perform(GhprbPullRequestMerge.java:147)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1775)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Build step 'Github Pull Request Merger' marked build as failure
```

```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.Ghprb.isAdmin(Ghprb.java:140)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequestMerge.perform(GhprbPullRequestMerge.java:134)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1775)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Build step 'Github Pull Request Merger' marked build as failure
```

**Comment by waltherg** [comment]
I am getting the isAdmin null pointer exception (not the isOwnCode) with the following project-specific settings:

Merge comment `.*merge\W+this\W+please.*`
Only merge on trigger phrase ticked
Only Admin can merge code ticked
Disallow merging own code? ticked

Oddly when leaving the ticks unchanged to the above but changing the merge comment to `merge` then the isAdmin null pointer exception disappears.

**Comment by benSlaughter** [comment]
I only see this occur when the build is triggered automatically, I think that both the `isOwnCode` and `isAdmin` methods require a GHUser, and because there is not one provided it creates a NPE
If you trigger the build by comment then the methods have a GHUser

I believe the fix needs to be something along the lines of
If the GHUser is null then return false
I could give it a go, but I think there are many others much more skilled than I :)

**Comment by DavidTanner** [comment]
I am working on a patch for the credentials, I will include it there.

**Comment by DavidTanner** [comment]
Please check again with 1.24.5
