### ISSUE TITLE
ghprb 1.24.3 doesn't work with GitHub Enterprise 2.2

### ISSUE THREAD

**Issue by serj-lotutovici** [janinko/ghprb#299]
After updating the GitHub Enterprise to the latest version ghprb doesn't work...

I keep getting these exceptions in logs:

```
Jun 29, 2015 2:42:23 PM INFO org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
Trying to send comment.
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.2/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:179)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:160)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: PATH_TO_REPO/statuses/f371f632d0f3868c5024c5a5eee90b771ed08e01
	at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 12 more
Caused by: java.io.FileNotFoundException: PATH_TO_REPO/statuses/f371f632d0f3868c5024c5a5eee90b771ed08e01
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 13 more

Jun 29, 2015 2:42:23 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository addComment
Couldn't add comment to pull request #564: 'Build finished. No test results found.
'
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.2/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.Requester.to(Requester.java:179)
	at org.kohsuke.github.GHIssue.comment(GHIssue.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.addComment(GhprbRepository.java:200)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.addComment(GhprbRepository.java:184)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.commentOnFailure(GhprbRepository.java:172)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:147)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: PATH_TO_REPO/issues/564/comments
	at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 14 more
Caused by: java.io.FileNotFoundException: PATH_TO_REPO/issues/564/comments
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 15 more
```

The plugin pulls the code and triggers the build, but doesn't update the PR.

Also if the PR is updated with a commit, the logs show this:

```
Pull request #564 was updated on PATH_TO_REPO at 6/29/15 2:39 PM by User:serj-lotutovici
Jun 29, 2015 2:50:00 PM INFO org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.2/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildTriggered(GhprbSimpleStatus.java:113)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:44)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:276)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:268)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:173)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:134)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:115)
	at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:135)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:208)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: PATH_TO_REPO/statuses/34b20245fa12f207e1824fc3fe6a35f9e53fe17b
	at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 21 more
Caused by: java.io.FileNotFoundException: PATH_TO_REPO/statuses/34b20245fa12f207e1824fc3fe6a35f9e53fe17b
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 22 more
```

The user who's credentials (aka token) are used for the plugin has full admin access to the repo

**Comment by DavidTanner** [comment]
please update to 1.24.4 when it is available.  There were some issues with the switch to credentials.

**Comment by serj-lotutovici** [comment]
Thx @DavidTanner! When the 1.24.4 release is planed?

**Comment by DavidTanner** [comment]
The Jenkins team has a job set up that runs six times a day to update the update-center json file.  I think it runs at either 9 or 11, then takes a bit to finish.

**Comment by serj-lotutovici** [comment]
@DavidTanner ok, thx)

**Comment by sgykfjsm** [comment]
I have same issue now.
I have updated to 1.24.4 but not solve
My GHE is v2.1.6

**Comment by serj-lotutovici** [comment]
Can confirm @sgykfjsm. Just updated to 1.24.4 and the issue persists... with the same stack trace as above...

**Comment by DavidTanner** [comment]
@serj-lotutovici @sgykfjsm Is this issue still present with 1.24.8?

**Comment by sgykfjsm** [comment]
@DavidTanner This issue is not present now with 1.25. Thank you for great job !

**Comment by sgykfjsm** [comment]
Ah...I'm sorry for my poor confirmation.
After I have configured 2nd credentials, same stack trace is displayed.
Even if removed 2nd credentials, the issue is persist.

**Comment by DavidTanner** [comment]
Please post logs set to finest for the plugin

**Comment by sgykfjsm** [comment]
1st: When 1 credential only. This credentials is created previously and has permissions below.
- admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user
```
Jul 13, 2015 3:35:00 PM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger
Running trigger for ghprb-git.XXXXXXXX.com
Jul 13, 2015 3:35:00 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 6e8b96c3-d5ba-4d12-b24a-76ca51367a2b, using context ghprb-git.XXXXXXXX.com for url http://git.XXXXXXXX.com/api/v3
Jul 13, 2015 3:35:00 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 1 credentials
Jul 13, 2015 3:35:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ghprb-git.XXXXXXXX.com
Jul 13, 2015 3:35:00 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #3 was updated on USERNAME/hello_world at 7/13/15 3:34 PM by User:USERNAME
Jul 13, 2015 3:35:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Retest phrase
Jul 13, 2015 3:35:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Admin User:USERNAME gave retest phrase
Jul 13, 2015 3:35:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jul 13, 2015 3:35:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jul 13, 2015 3:35:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
Jul 13, 2015 3:35:00 PM INFO org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.1/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildTriggered(GhprbSimpleStatus.java:113)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:48)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:288)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:280)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:154)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:134)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:115)
	at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:220)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: http://git.XXXXXXXX.com/api/v3/repos/USERNAME/hello_world/statuses/59b3e1d176730debc6e53c8565d8367ab768e348
	at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 21 more
Caused by: java.io.FileNotFoundException: http://git.XXXXXXXX.com/api/v3/repos/USERNAME/hello_world/statuses/59b3e1d176730debc6e53c8565d8367ab768e348
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 22 more
```
This log said "commentOnFailure", but actually comment was written and build has done.

---

2nd: When added credentials. At this moment, 2 credentials is there.This credentials is created previously  for other domain GHE and has permissions below.
- admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user
```
Starting the ghprb trigger for the ghprb-git-second.XXXXXXXX.com job; newInstance is true
Jul 13, 2015 3:48:58 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ee139bd3-d791-436f-a4b5-13677c73f3d1, using context ghprb-git-second.XXXXXXXX.com for url http://git-second.XXXXXXXX.com/api/v3
Jul 13, 2015 3:48:58 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Jul 13, 2015 3:48:58 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ghprb-git-second.XXXXXXXX.com
Jul 13, 2015 3:48:59 PM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger stop
Stopping the ghprb trigger for project ghprb-git-second.XXXXXXXX.com
Jul 13, 2015 3:48:59 PM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger start
Starting the ghprb trigger for the ghprb-git-second.XXXXXXXX.com job; newInstance is true
Jul 13, 2015 3:48:59 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ee139bd3-d791-436f-a4b5-13677c73f3d1, using context ghprb-git-second.XXXXXXXX.com for url http://git-second.XXXXXXXX.com/api/v3
Jul 13, 2015 3:48:59 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Jul 13, 2015 3:48:59 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ghprb-git-second.XXXXXXXX.com
Jul 13, 2015 3:49:00 PM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger
Running trigger for ghprb-git-second.XXXXXXXX.com
Jul 13, 2015 3:49:00 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for ee139bd3-d791-436f-a4b5-13677c73f3d1, using context ghprb-git-second.XXXXXXXX.com for url http://git-second.XXXXXXXX.com/api/v3
Jul 13, 2015 3:49:00 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Jul 13, 2015 3:49:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ghprb-git-second.XXXXXXXX.com
Jul 13, 2015 3:49:00 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Created Pull Request #2 on USERNAME/hello_world by USERNAME () updated at: 7/13/15 10:54 AM SHA: 227b82ab8110ea794afbb569165f8ad3b72dd775
Jul 13, 2015 3:49:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jul 13, 2015 3:49:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jul 13, 2015 3:49:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
Jul 13, 2015 3:49:00 PM INFO org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.1/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildTriggered(GhprbSimpleStatus.java:113)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:48)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:288)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:280)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:154)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:134)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:115)
	at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:220)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: http://git-second.XXXXXXXX.com/api/v3/repos/USERNAME/hello_world/statuses/227b82ab8110ea794afbb569165f8ad3b72dd775
	at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 21 more
Caused by: java.io.FileNotFoundException: http://git-second.XXXXXXXX.com/api/v3/repos/USERNAME/hello_world/statuses/227b82ab8110ea794afbb569165f8ad3b72dd775
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 22 more
```

---

3rd: Using credentials created ghprb-plugin at Configure System. This credentials permissions is below.
- repo   repo:status 
```
Looking up credentials for 36078024-cf13-4b8e-80b6-5d0270d1ab6c, using context ghprb-git.XXXXXXXX.com for url http://git.XXXXXXXX.com/api/v3
Jul 13, 2015 4:02:00 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 3 credentials
Jul 13, 2015 4:02:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ghprb-git.XXXXXXXX.com
Jul 13, 2015 4:02:00 PM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #3 was updated on USERNAME/hello_world at 7/13/15 4:01 PM by User:USERNAME
Jul 13, 2015 4:02:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Retest phrase
Jul 13, 2015 4:02:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Admin User:USERNAME gave retest phrase
Jul 13, 2015 4:02:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Jul 13, 2015 4:02:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Jul 13, 2015 4:02:00 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
```
It seems fine. Build is successful. But comments on GHE is not shown.

**Comment by DavidTanner** [comment]
Use the credentisls tests on the global configure page to see if the users/token have push/pull/admin access to the repositories you want to hit.

**Comment by sgykfjsm** [comment]
I confirmed credentials has permissions to Push and Pull, and re-tried. Jenkins worked successfully without stack trace.
But below messages is shown at Console Output in Jenkins job. Is this expected?
```
Setting status of 59b3e1d176730debc6e53c8565d8367ab768e348 to SUCCESS with url http://JENKINS-HOST/job/ghprb-test/20/ and message: 'Build finished. No test results found.'
```

**Comment by DavidTanner** [comment]
That is expected output
