### ISSUE TITLE
Failing to set status when build is auto-started

### ISSUE THREAD

**Issue by shehzan10** [janinko/ghprb#307]
I'm facing quite the conundrum. My pull request jobs fail to set the status only when the build is started either via admin or via comments (test this please, etc).

However, when I start the same pull request manually (using origin/.... in the parameter), the statuses are set fine, with the exception that they use the job name rather than the context name (not really an issue for me).

I have noticed this happening on Windows, Linux and OSX slaves. I have made sure that all the slave keys and the master key are added to my bot user. That said, one of my Linux pull request jobs sets the status correctly even with automatic starts.

I don't think this is a permissions issue (as stated in the stack trace); if it were, then the manually started builds should fail too, which is not happening.

One thing is that my bot is member of the team which has read and write access to the repo (not owner rights).

I am currently using Jenkins 1.619, GHPRB 1.24.5, Github Plugin 1.11.3.

Here is a stack trace of the failure:
```
GitHub pull request #889 of commit 73dbeb9deed3b2b6d612a55926e22308fbc61e7f, no merge conflicts.
Setting status of 73dbeb9deed3b2b6d612a55926e22308fbc61e7f to PENDING with url http://ci.arrayfire.org/job/arrayfire-windows-pull/103/ and message: 'Build started, sha1 is merged'
Using context: jenkins/Windows-x64
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
	at org.kohsuke.github.Requester._to(Requester.java:245)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:117)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:73)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:108)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:19)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:215)
	at hudson.model.Run.execute(Run.java:1740)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/arrayfire/arrayfire/statuses/73dbeb9deed3b2b6d612a55926e22308fbc61e7f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 12 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/arrayfire/arrayfire/statuses/73dbeb9deed3b2b6d612a55926e22308fbc61e7f
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 13 more
```

**Comment by shehzan10** [comment]
One thing I missed, I tried using a fork of the repository that was owned by the bot as a test case for the pull request. Even in this case it failed to set the status.
That is, I used the forked repo as the github url in the job setup, created a dummy branch, opened the pull request from the dummy branch to the default branch.

**Comment by DavidTanner** [comment]
Please add more logging, then send those logs over.  You might see that the credentials used aren't the ones you intended.

**Comment by shehzan10** [comment]
I'm trying to setup the logging and try that out. (I'm assuming this involves changing the log level of the default logger to "all" from "info"?)

On your second point, the credentials do not wary irrespective of whether the build was started using the parameter or the comments on github. Any thoughts on this?

**Comment by DavidTanner** [comment]
Create a logger for org.jenkinsci.plugins.ghprb,  Then you can set that to finest and get just the logs from the plugin.

**Comment by shehzan10** [comment]
Thanks for that suggestion. It was giving an error about not finding the credentials (something might have got mixed up). It was using secret text before. Changed it to user name and password and its all good now.

Thanks a lot!
