### ISSUE TITLE
PR Building not able commit status in second job

### ISSUE THREAD

**Issue by obuckley-kenzan** [janinko/ghprb#311]
I have been able to successfully setup the Github PR Builder with one of my Jenkins jobs and one of my private repos in my organization.  I have gone and setup a second job for a second, essentially cloning the Jenkins job but it is failing trying to commit the status to the PR.

```
message: Build started, sha1 is merged
Could not update commit status of the Pull Request on GitHub.
org.jenkinsci.plugins.ghprb.extensions.GhprbCommitStatusException: Build started, sha1 is merged
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:88)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildStart(GhprbSimpleStatus.java:69)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:85)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:19)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:213)
	at hudson.model.Run.execute(Run.java:1747)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

I am using this same configuration in each job (same admin, whitelist, organization whitelist values, etc).  I have made sure to check the webhook configurations for both repos and made sure to double check the personal access tokens section of my profile but I don't think there would be anything wrong there since the first job / repo combo is working.

I am using v1.22 of the plugin and v1.605 of Jenkins.

Any thoughts / feedback would be appreciated.

**Comment by obuckley-kenzan** [comment]
Nevermind, it seems maybe the missing config value was setting a value to Commit Status Context
