### ISSUE TITLE
Asking for admin verify even if "Build every pull request automatically without asking" is checked

### ISSUE THREAD

**Issue by nwalke** [janinko/ghprb#325]
I have a project which I want to build every PR without the plugin asking for admin verification.  I checked the box "build every PR..." but it still posts a comment on each PR change "Can an admin verify?"  Even though it posts this comment, the job still runs.

How can I disable this comment?

**Comment by nwalke** [comment]
Here's what my configuration looks like in the job:
![screen shot 2015-09-09 at 11 28 41 am](https://cloud.githubusercontent.com/assets/1617620/9767875/faf3715e-56e5-11e5-8eee-38114d891ace.png)

I've tried disabling the trigger on the job and re-adding it, but that did not help.

**Comment by nwalke** [comment]
Also my trigger setup in the job in case that matters:
![screen shot 2015-09-09 at 11 30 16 am](https://cloud.githubusercontent.com/assets/1617620/9767910/330424da-56e6-11e5-9aeb-ea09e7e38c65.png)

**Comment by nwalke** [comment]
Here's log output when a new PR is opened:
```
Sep 09, 2015 11:40:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Sep 09, 2015 11:40:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Checking PR #5,215 for rednovalabs/fms
Sep 09, 2015 11:40:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Created Pull Request #5,215 on rednovalabs/fms by nwalke (null) updated at: 9/9/15 11:40 AM SHA: 8af88de955ca0b006577f4020a410162c03359c0
Sep 09, 2015 11:40:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Sep 09, 2015 11:40:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Checking PR #5,215 for rednovalabs/fms
Sep 09, 2015 11:40:03 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Author of #5,215 nwalke on rednovalabs/fms not in whitelist!
Sep 09, 2015 11:40:04 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest 
Created Pull Request #5,215 on rednovalabs/fms by nwalke (null) updated at: 9/9/15 11:40 AM SHA: 8af88de955ca0b006577f4020a410162c03359c0
Sep 09, 2015 11:40:04 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: issue_comment
Sep 09, 2015 11:40:04 AM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Checking issue comment 'org.kohsuke.github.GHIssueComment@1c776c53' for repo rednovalabs/fms
Sep 09, 2015 11:40:04 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #5,215 was updated on rednovalabs/fms at 9/9/15 11:40 AM by User:rednovalabs-jenkins
Sep 09, 2015 11:40:05 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbTrigger getRepository
The ghprb trigger for null wasn't properly started - helper is null
Sep 09, 2015 11:40:05 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Unable to process web hook for: null
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbWebHook.handleWebHook(GhprbWebHook.java:33)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.doIndex(GhprbRootAction.java:90)
	at sun.reflect.GeneratedMethodAccessor247.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$2.dispatch(MetaClass.java:165)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at org.jenkinsci.plugins.modernstatus.ModernStatusFilter.doFilter(ModernStatusFilter.java:52)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:129)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

You can see in the log output that it complains that I'm not in the whitelist, and then it receives a webhook for the comment it made on the PR right before it errors out.

**Comment by DavidTanner** [comment]
i am going to say you probably have another job set up for that repo that isn't complete.

**Comment by nwalke** [comment]
Interesting...  I do have several jobs that use that same repo.  I'll go through and check them.

**Comment by nwalke** [comment]
You're absolutely correct.  I had another job with ghprb checked, but I didn't have the hook set up until I wanted to enable it for this new job.  

Thanks for the help, and sorry for the brain dump of stuff.  Just wanted to make sure I provided any relevant details.
