### ISSUE TITLE
ghprb goes into recursive calls when github repo's don't exist

### ISSUE THREAD

**Issue by JensTimmerman** [janinko/ghprb#345]
```
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.github.com/repos/hpcugent/test-repo with spaces in name
	at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:458)
	at org.kohsuke.github.Requester._to(Requester.java:227)
	at org.kohsuke.github.Requester.to(Requester.java:194)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:323)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:83)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:47)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
```

this keeps on recursing, so jenkins just hangs when trying to load this plugin.

**Comment by WynyardEngineering** [comment]
We see a similar thing when github (we use github enterprise) uses a cert that Java doesn't like for one reason or another:

```java.lang.StackOverflowError
	at java.lang.Character.digit(Unknown Source)
	at java.lang.Character.digit(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at sun.security.util.ObjectIdentifier.<init>(Unknown Source)
	at sun.security.x509.X509CertImpl.getExtensionValue(Unknown Source)
	at sun.security.provider.certpath.AdaptableX509CertSelector.match(Unknown Source)
	at sun.security.provider.certpath.CollectionCertStore.engineGetCertificates(Unknown Source)
	at java.security.cert.CertStore.getCertificates(Unknown Source)
	at sun.security.provider.certpath.Builder.addMatchingCerts(Unknown Source)
	at sun.security.provider.certpath.ForwardBuilder.getMatchingCACerts(Unknown Source)
	at sun.security.provider.certpath.ForwardBuilder.getMatchingCerts(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.depthFirstSearchForward(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.depthFirstSearchForward(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.depthFirstSearchForward(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.buildForward(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.buildCertPath(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GitHub.getRateLimit(GitHub.java:243)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:71)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:47)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
[etc]
```

This causes a huge dump (~50MB) in the Jenkins log, and any job that uses the plugin fails to load.

**Comment by gimler** [comment]
same problem here it works before but not with the actual version of the plugin

```
Oct 27, 2015 8:24:21 AM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: No connection returned to GitHub server!
Oct 27, 2015 8:24:21 AM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: No connection returned to GitHub server!
Oct 27, 2015 8:24:21 AM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: No connection returned to GitHub server!
Oct 27, 2015 8:24:21 AM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: No connection returned to GitHub server!
Oct 27, 2015 8:24:21 AM org.jenkinsci.plugins.ghprb.GhprbGitHubAuth getConnection
SEVERE: Unable to connect using credentials: 51a96d28-e3d8-4cf7-a1bd-d99011e45017
javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.j: PKIX path building failed: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=..., C=DE is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:85)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:541)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1686)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1684)
	at java.security.AccessController.doPrivileged(AccessController.java:330)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1682)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1255)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:479)
	at com.ibm.net.ssl.www2.protocol.https.b.getResponseCode(b.java:40)
	at org.kohsuke.github.Requester.handleApiError(Requester.java:489)
	at org.kohsuke.github.Requester._to(Requester.java:248)
	at org.kohsuke.github.Requester.to(Requester.java:194)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:264)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:140)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:195)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.getConnection(GhprbGitHubAuth.java:148)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.getGitHub(GhprbTrigger.java:321)
	at org.jenkinsci.plugins.ghprb.GhprbGitHub.get(GhprbGitHub.java:23)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:66)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:47)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
...
```

**Comment by jurajseffer** [comment]
Just getting the same now.

```
May 11 23:32:40 prod-jenkins-01 java[3247]: INFO: Starting the ghprb trigger for the test job; newInstance is false
May 11 23:33:47 prod-jenkins-01 java[3247]: May 11, 2016 11:33:47 PM hudson.model.AbstractProject onLoad
May 11 23:33:47 prod-jenkins-01 java[3247]: WARNING: could not start trigger while loading project 'analytics-bundle'
May 11 23:33:47 prod-jenkins-01 java[3247]: java.lang.StackOverflowError
May 11 23:33:47 prod-jenkins-01 java[3247]: at java.security.AccessController.doPrivileged(Native Method)
May 11 23:33:47 prod-jenkins-01 java[3247]: at sun.net.www.protocol.http.HttpURLConnection.<init>(HttpURLConnection.java:741)
May 11 23:33:47 prod-jenkins-01 java[3247]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.<init>(AbstractDelegateHttpsURLConnection.java:55)
May 11 23:33:47 prod-jenkins-01 java[3247]: at sun.net.www.protocol.https.DelegateHttpsURLConnection.<init>(DelegateHttpsURLConnection.java:64)
May 11 23:33:47 prod-jenkins-01 java[3247]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:86)
May 11 23:33:47 prod-jenkins-01 java[3247]: at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
May 11 23:33:47 prod-jenkins-01 java[3247]: at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
May 11 23:33:47 prod-jenkins-01 java[3247]: at java.net.URL.openConnection(URL.java:982)
May 11 23:33:47 prod-jenkins-01 java[3247]: at hudson.ProxyConfiguration.open(ProxyConfiguration.java:220)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.HttpConnectorWithJenkinsProxy.connect(HttpConnectorWithJenkinsProxy.java:12)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.kohsuke.github.Requester.setupConnection(Requester.java:425)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.kohsuke.github.Requester._to(Requester.java:222)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.kohsuke.github.Requester.to(Requester.java:194)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.kohsuke.github.GitHub.getRateLimit(GitHub.java:245)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:71)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:47)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbPullRequest.init(GhprbPullRequest.java:103)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.init(GhprbRepository.java:51)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:334)
May 11 23:33:47 prod-jenkins-01 java[3247]: at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:269)
```
