### ISSUE TITLE
Exception 'Failed to instantiate class org.jenkinsci.plugins.ghprb.GhprbTrigger' when removing trigger setup section in both plugin and job configurations

### ISSUE THREAD

**Issue by leaxfm** [janinko/ghprb#372]
I faced the problem trying to get rid of the default commit statuses. Just removed these sections from both plugin and job configurations.

The same problem was already described in #351, but it's closed by author now. Anyway, it is not the normal behaviour, I suppose.

Steps:

* Manage Jenkins - Confiure - for GitHub Pull Request Builder delete the block "Update commit status during build" - Save
* Configure Job - for GitHub Pull Request Builder also delete the same block (Trigger Setup) - Save. Everything's just fine so far.
* Configure Job again - doing no matter what - Save. The result:

```
A problem occurred while processing the request. Please check our bug tracker to see if a similar problem has already been reported. If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem. If you think this is a new issue, please file a new issue. When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins. The users list might be also useful in understanding what has happened.

Stack trace

javax.servlet.ServletException: java.lang.RuntimeException: Failed to instantiate class org.jenkinsci.plugins.ghprb.GhprbTrigger from {"gitHubAuthId":"0ca74f26-7261-4466-99cd-c79a82365cbf","adminlist":"jenkins2gissquare leaxfm","useGitHubHooks":true,"triggerPhrase":"!test","onlyTriggerPhrase":false,"autoCloseFailedPullRequests":false,"skipBuildPhrase":".*\\[skip\\W+ci\\].*","displayBuildErrorsOnDownstreamBuilds":false,"cron":"H/5 * * * *","whitelist":"","orgslist":"","allowMembersOfWhitelistedOrgsAsAdmin":false,"permitAll":false,"buildDescTemplate":"","whiteListTargetBranches":{"branch":""},"extensions":{"stapler-class":"","$class":""}}
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to instantiate class org.jenkinsci.plugins.ghprb.GhprbTrigger from {"gitHubAuthId":"0ca74f26-7261-4466-99cd-c79a82365cbf","adminlist":"jenkins2gissquare leaxfm","useGitHubHooks":true,"triggerPhrase":"!test","onlyTriggerPhrase":false,"autoCloseFailedPullRequests":false,"skipBuildPhrase":".*\\[skip\\W+ci\\].*","displayBuildErrorsOnDownstreamBuilds":false,"cron":"H/5 * * * *","whitelist":"","orgslist":"","allowMembersOfWhitelistedOrgsAsAdmin":false,"permitAll":false,"buildDescTemplate":"","whiteListTargetBranches":{"branch":""},"extensions":{"stapler-class":"","$class":""}}
	at hudson.model.Descriptor.newInstance(Descriptor.java:586)
	at hudson.model.AbstractProject.buildDescribable(AbstractProject.java:1897)
	at hudson.model.AbstractProject.submit(AbstractProject.java:1875)
	at hudson.model.Project.submit(Project.java:230)
	at hudson.model.Job.doConfigSubmit(Job.java:1212)
	at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:796)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 63 more
Caused by: java.lang.IllegalArgumentException: Failed to instantiate class org.jenkinsci.plugins.ghprb.GhprbTrigger from {"gitHubAuthId":"0ca74f26-7261-4466-99cd-c79a82365cbf","adminlist":"jenkins2gissquare leaxfm","useGitHubHooks":true,"triggerPhrase":"!test","onlyTriggerPhrase":false,"autoCloseFailedPullRequests":false,"skipBuildPhrase":".*\\[skip\\W+ci\\].*","displayBuildErrorsOnDownstreamBuilds":false,"cron":"H/5 * * * *","whitelist":"","orgslist":"","allowMembersOfWhitelistedOrgsAsAdmin":false,"permitAll":false,"buildDescTemplate":"","whiteListTargetBranches":{"branch":""},"extensions":{"stapler-class":"","$class":""}}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:602)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:404)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:400)
	at hudson.model.Descriptor.newInstance(Descriptor.java:577)
	... 78 more
Caused by: java.lang.IllegalArgumentException: Failed to convert the extensions parameter of the constructor public org.jenkinsci.plugins.ghprb.GhprbTrigger(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,java.lang.String,java.util.List,java.lang.Boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.util.List) throws antlr.ANTLRException
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:699)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:600)
	... 81 more
Caused by: java.lang.IllegalArgumentException: Failed to instantiate class org.jenkinsci.plugins.ghprb.extensions.GhprbExtension from {"stapler-class":"","$class":""}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:602)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:638)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:404)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:697)
	... 83 more
Caused by: java.lang.IllegalArgumentException: Class  is specified in JSON, but no such class found in classLoader hudson.PluginManager$UberClassLoader
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:596)
	... 86 more
Caused by: java.lang.ClassNotFoundException: cached miss for 
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1170)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:591)
	... 86 more
```

**Comment by alpegon** [comment]
+1 
I'm facing the same issue.
When trying to modify the second time the configuration of the plugin in a job, this error appears.
