### ISSUE TITLE
Re running tests on the same commit a certain number of times can cause NPEs

### ISSUE THREAD

**Issue by farmdawgnation** [janinko/ghprb#389]
I've observed behavior wherein we get a NullPointerException when the plugin attempts to start a job if we've attempted to re-run tests against the same head commit multiple times. The problem appears to be resolved by pushing a new commit.

The stack trace is as follows:

```
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.startJob(GhprbTrigger.java:298)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:78)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:325)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:318)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:202)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:338)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:590)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction.doIndex(GhprbRootAction.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$2.dispatch(MetaClass.java:165)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$13.dispatch(MetaClass.java:411)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
```

It appears to be due to some inability to retrieve the author. The only thing I can think is that after a certain amount of requests GitHub starts paginating the responses for status and that's not handled correctly? Though, perhaps it's something else entirely.

I'll try to find time to look into this but if I don't I wanted to file the report so y'all were aware.

**Comment by gjacquet** [comment]
We are having the same issue. I guess that happens when the last build for the pull request no longer exists.
```java
        GhprbPullRequest pr = getRepository().getPullRequest(cause.getPullID());
        String lastBuildId = pr.getLastBuildId();
        BuildData buildData = null;
        if (!(job instanceof MatrixProject) && !StringUtils.isEmpty(lastBuildId)) {
            AbstractBuild<?, ?> lastBuild = job.getBuild(lastBuildId);
            buildData = lastBuild.getAction(BuildData.class);
        }
```
It looks like the last job ID is set but no longer exists in Jenkins. It is often the case in our setup as we keep only a few builds (something between 20 and 50) so after less than a day PR builds can no longer be triggered.

Fix looks simple enough though. It seems that adding a null check would be enough.

**Comment by ephemeral** [comment]
+1 

By the way, do you guys know if we should use this project to report issues? Or use the official jenkins ci repo with the release tags (https://github.com/jenkinsci/ghprb-plugin) ?

**Comment by gjacquet** [comment]
Here's the PR: https://github.com/jenkinsci/ghprb-plugin/pull/278
