### ISSUE TITLE
Test phrase not triggering build

### ISSUE THREAD

**Issue by austek-mdsol** [janinko/ghprb#392]
Using test phrase is throwing a NPE on Jenkins 1.649

`org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@10ac1c2[Pinnacles]
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.startJob(GhprbTrigger.java:298)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:78)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:325)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:318)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:161)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:174)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:154)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:281)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by lsmolic** [comment]
:+1:

**Comment by DavidTanner** [comment]
What version of the plugin are you running?

**Comment by walgitrus** [comment]
For me, it's version 1.30.3

**Comment by DavidTanner** [comment]
Please upgrade to the latest and try again

**Comment by Pr60** [comment]
I have kind of related problem. Any idea on how to fix this - https://stackoverflow.com/questions/58958189/ghprb-plugin-in-jenkins-unable-to-trigger-build
