### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jsposato** [janinko/ghprb#395]
Jenkins version 1.646, GHPR builder plugin version 1.30.4

github project URL is filled out and correct.

`Mar 01, 2016 9:16:00 PM hudson.triggers.Trigger checkTriggers
WARNING: org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@1ef74e86[ww_ios_users_pull_request_builder]
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.getConnection(GhprbGitHubAuth.java:201)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.getGitHub(GhprbTrigger.java:370)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:87)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:128)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:281)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by DavidTanner** [comment]
Make sure you have set up some kind of credentials on the global setup page for Ghprb

**Comment by jsposato** [comment]
ok, so somehow updating the plugin changed the global config for user...  Any chance a more meaningful log message (Authentication failed) could be added?

**Comment by DavidTanner** [comment]
I haven't ever run into that error.  I think the fix would be to check if credentialsId is null and return instead if it is.

**Comment by DavidTanner** [comment]
I can't figure out how that could be null.  There are a lot of places that this gets used, and this is the first it has ever been null.
