### ISSUE TITLE
Exceeded rate limit for repository

### ISSUE THREAD

**Issue by AlexChesters** [janinko/ghprb#407]
Jenkins version: 2.0
GHPRB version: 1.31.4

I'm getting the following errors trying to use this plugin:

```
Exceeded rate limit for repository
May 05, 2016 8:20:03 AM WARNING hudson.model.listeners.RunListener report
RunListener failed
java.lang.NullPointerException
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:248)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:208)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:192)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:202)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by ingvagabund** [comment]
The same here. Downgrading back to previous 1.29.8 helps.

**Comment by ingvagabund** [comment]
Taking back, it works. Just had to recreate ``Credentials`` in ``Jenkins > Configuration`` instead of via ``Jenkins > Credentials``. Strange.

**Comment by RoyTinker** [comment]
Recreating credentials is only a temporary fix.
