### ISSUE TITLE
Jenkins job not getting triggered when new PR is created

### ISSUE THREAD

**Issue by Ramesh7** [janinko/ghprb#444]
I have configured jenkins job with allowing respective orginasation in whitlisting for auto triggering build but it's not getting triggered whenever new PR is get created. Repos are private. User is able to clone the repo.
Here is the error  
```
SEVERE: Could not retrieve GitHub repository named cloud-ops/cloud-control (Do you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:553)
	at org.kohsuke.github.Requester._to(Requester.java:264)
	at org.kohsuke.github.Requester.to(Requester.java:205)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:338)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:112)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:130)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:294)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/cloud-ops/cloud-control
	at sun.reflect.GeneratedConstructorAccessor144.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:492)
	at org.kohsuke.github.Requester._to(Requester.java:243)
	... 15 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/cloud-ops/cloud-control
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:486)
	... 16 more
```
If I hit api url https://api.github.com/repos/cloud-ops/cloud-control :
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

**Comment by Ramesh7** [comment]
There was issue with adding jenkins user to repo as collaborator with write access.
