### ISSUE TITLE
Couldn't find any revision to build. Verify the repository and branch configuration for this job.

### ISSUE THREAD

**Issue by Nimrodda** [janinko/ghprb#448]
Pull requests are failing to build due to the error below. I noticed there's a similar [issue](https://github.com/janinko/ghprb/issues/347) already open, but the fix presented there, i.e. updating the plugin to the latest version - doesn't change anything.
Does the plugin support Jenkins 2?

Here's my setup:
Jenkins version **2.27**
Plugin version 1.33.1
Mac OS X El Capitan

```
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
ERROR: Step ‘Set build status on GitHub commit’ aborted due to exception: 
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
	at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:38)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:111)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:90)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:401)
Finished: FAILURE
```

**Comment by shapeofarchitect** [comment]
@Nimrodda  sorry for the comment on closed issue. Were you able to find the solution to this ? I am seeing this constantly and not been able to figure out what's wrong. 

My setup is :
Jenkins (CLoudbees CI) 
SCM is : Bitbucket repo (Plugin Bitbucket Source Branch Plugin)

It recently started happening now only.

Thanks
