### ISSUE TITLE
Could not update commit status of the Pull Request on GitHub.

### ISSUE THREAD

**Issue by nurupo** [janinko/ghprb#453]
I have "Build Triggers -> GitHub Pull Request Builder -> Trigger Setup -> Update commit status during build -> Commit status URL" set to `${BUILD_URL}console`. This seems to fail to set the commit status URL for when the build is triggered. It seems to set it correctly when the build is started though. Are environment variables not available when the build is just triggered but not started?

```
Dec 17, 2016 6:18:00 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR
Checking PR #4 for job test-job
Dec 17, 2016 6:18:01 AM INFO org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
Pull request #4 was updated/initialized on nurupo/test at 12/17/16 6:17 AM by null (PR update)
Dec 17, 2016 6:18:01 AM INFO org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
Could not update commit status of the Pull Request on GitHub.
java.io.IOException: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"target_url","message":"target_url must use http(s) scheme"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
	at org.kohsuke.github.Requester.to(Requester.java:213)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:953)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildTriggered(GhprbSimpleStatus.java:145)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:76)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:362)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:355)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:168)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:386)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR(GhprbTrigger.java:619)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$2.run(GhprbRootAction.java:252)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 422, message: 'Unprocessable Entity' for URL: https://api.github.com/repos/nurupo/test/statuses/1330d1a6ddc3a067fdb056e4ac94d99efda2c5b6
	at org.kohsuke.github.Requester.parse(Requester.java:540)
	at org.kohsuke.github.Requester._to(Requester.java:251)
	... 10 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/nurupo/test/statuses/1330d1a6ddc3a067fdb056e4ac94d99efda2c5b6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1719)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1717)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1715)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1285)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:524)
	... 11 more
Caused by: java.io.IOException: Server returned HTTP response code: 422 for URL: https://api.github.com/repos/nurupo/test/statuses/1330d1a6ddc3a067fdb056e4ac94d99efda2c5b6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1670)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:514)
	... 11 more

Dec 17, 2016 6:18:01 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository commentOnFailure
Could not update commit status of the Pull Request on GitHub.
Dec 17, 2016 6:19:53 AM INFO hudson.model.Run execute
test-job #20 main build action completed: SUCCESS
```

**Comment by MikhailTymchukDX** [comment]
I have same issue too. Is it safe to ignore it?

**Comment by Chrislevi** [comment]
Any news? seems like it just happend, didnt upgrade anything. 

Jenkins 2.75
ghprb 1.39
