### ISSUE TITLE
The new pull request hook integration does not work

### ISSUE THREAD

**Issue by rocketraman** [janinko/ghprb#50]
I tried to configure a repository in an organization using the pull request hook integration. I see this error in the logs:

```
Apr 29, 2013 5:47:13 PM org.jenkinsci.plugins.ghprb.GhprbRepository createHook
SEVERE: Couldn't create web hook for repositorymy-org/my-repo
java.io.FileNotFoundException: https://api.github.com/repos/my-org/my-repo/hooks
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1434)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
        at org.kohsuke.github.Requester.parse(Requester.java:297)
        at org.kohsuke.github.Requester._to(Requester.java:173)
        at org.kohsuke.github.Requester.to(Requester.java:139)
        at org.kohsuke.github.GHRepository.getHooks(GHRepository.java:385)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.hookExist(GhprbRepository.java:148)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.createHook(GhprbRepository.java:160)
        at org.jenkinsci.plugins.ghprb.Ghprb$Builder.build(Ghprb.java:177)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:61)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.start(GhprbTrigger.java:37)
        at hudson.model.AbstractProject.submit(AbstractProject.java:1952)
        at hudson.maven.MavenModuleSet.submit(MavenModuleSet.java:1115)
        at hudson.model.Job.doConfigSubmit(Job.java:1076)
        at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:755)
        ...
```

Access does require authentication.

**Comment by swapnil-kotwal-sp** [comment]
What would be possible reason for this. I have set admin user, access token. still it's not able to detect my repo which is here https://github.com/swapnil-kotwal-sp/TheInternetAutomation
```
←[31mApr 27, 2015 1:17:01 PM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: Could not retrieve GitHub repository named swapnil-kotwal-sp/TheInternetAutomation.git (Do
 you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.githu
b.com/v3"}
        at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
        at org.kohsuke.github.Requester._to(Requester.java:245)
        at org.kohsuke.github.Requester.to(Requester.java:191)
        at org.kohsuke.github.GitHub.getRepository(GitHub.java:320)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:66)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:76)
        at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:104)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:164)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:265)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown
 Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source
)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/swapnil-kotwal-sp/TheIntern
etAutomation.git
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at org.kohsuke.github.Requester.parse(Requester.java:451)
        at org.kohsuke.github.Requester._to(Requester.java:224)
        ... 16 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/swapnil-kotwal-sp/TheIntern
etAutomation.git
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
        at org.kohsuke.github.Requester.parse(Requester.java:447)
        ... 17 more

←[0m←[31mApr 27, 2015 1:17:02 PM org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
SEVERE: Could not retrieve GitHub repository named swapnil-kotwal-sp/TheInternetAutomation.git (Do
 you have properly set 'GitHub project' field in job configuration?)
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.githu
b.com/v3"}
        at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
        at org.kohsuke.github.Requester._to(Requester.java:245)
        at org.kohsuke.github.Requester.to(Requester.java:191)
        at org.kohsuke.github.GitHub.getRepository(GitHub.java:320)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:66)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:76)
        at org.jenkinsci.plugins.ghprb.Ghprb.run(Ghprb.java:104)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:164)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:265)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown
 Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source
)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/swapnil-kotwal-sp/TheIntern
etAutomation.git
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at org.kohsuke.github.Requester.parse(Requester.java:451)
        at org.kohsuke.github.Requester._to(Requester.java:224)
        ... 16 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/swapnil-kotwal-sp/TheIntern
etAutomation.git
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
        at org.kohsuke.github.Requester.parse(Requester.java:447)
        ... 17 more

```

**Comment by DavidTanner** [comment]
The problem is you have .git at the end of your url, I believe.

**Comment by swapnil-kotwal-sp** [comment]
@DavidTanner Thanks Man you solved it :)

**Comment by Protosac** [comment]
I'm experiencing the same issue, which is kind of strange. The broken PR tester is working on the same credentials as the ones which are working. So I'm not sure why it doesn't like the new repo or what is causing the error.

Exact same error as swap-nil above. Running in Ubuntu 12.04 LTS

**Comment by jackkav** [comment]
Worked after an update to 2.7

**Comment by badgujar** [comment]
I configured the Web-hook and see that all the request on that particular web-hook is getting response code 200 i.e. OK. But non of my Job in jenkins is getting triggered. I configured the jobs with all possible required configuration.  Any suggestions ?
